//! Entity structs mapped from database rows.
//!
//! Each struct derives `sqlx::FromRow` for direct deserialization from query results,
//! plus `Serialize`/`Deserialize` for API responses and JSON handling.

use agentforge_core::{
    AgentId, AgentStatus, AnalyticsEventId, AttachmentId, AuditLogId, DevEnvironmentId, EventId, FavoriteId,
    FeatureFlagId, GroupId, LicenseId, MemoryItemId, MessageId, OrgId, PluginId, ProjectId, PromptId, QuotaUsageId,
    ResourceProfileId, SettingId, SkillId, TeamId, TileId, UserId, VoiceProviderId, WorkspaceId,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// An organization (tenant). All business data is scoped to an organization.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Organization {
    pub id: OrgId,
    pub name: String,
    pub slug: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

/// A user account. May belong to multiple organizations.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct User {
    pub id: UserId,
    pub email: String,
    #[serde(skip_serializing)]
    pub password_hash: Option<String>,
    pub display_name: Option<String>,
    pub is_admin: bool,
    pub last_login_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

/// Organization membership join record.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct OrganizationMember {
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub role: String,
    pub created_at: DateTime<Utc>,
}

/// A managed coding agent running in a container.
/// Note: was "session" in the old TypeScript schema (migration 058 renamed it).
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Agent {
    pub id: AgentId,
    pub organization_id: OrgId,
    /// Workspace execution/access boundary. `project_id` is only the primary
    /// project context for routing and UI ownership.
    pub workspace_id: WorkspaceId,
    pub project_id: Option<ProjectId>,
    pub user_id: UserId,
    pub name: Option<String>,
    pub status: AgentStatus,
    pub container_id: Option<String>,
    /// Per-container HMAC-SHA256 key (issue #39). Generated by `start_agent`,
    /// injected into the sidecar as `HMAC_SECRET`, fetched by the
    /// orchestration result consumer to verify `SignedEnvelope` signatures.
    /// NEVER serialised — `#[serde(skip_serializing)]` keeps it out of every
    /// API response shape that re-uses this entity.
    #[serde(skip_serializing, default)]
    pub hmac_secret: Option<String>,
    /// Per-container NATS connect password (issue #38 phase 2). Generated by
    /// `start_agent`, embedded in the sidecar's `NATS_URL` as the user-info
    /// password, validated on CONNECT by the `services::auth_callout` service
    /// against the `user=<agent_uuid>` the sidecar presents. Cleared
    /// atomically with `hmac_secret` on `clear_container`. Deliberately stored
    /// separately from `hmac_secret` so a DB read of one secret does not also
    /// grant the other attacker surface (subject authorization vs. envelope
    /// forgery). NEVER serialised.
    #[serde(skip_serializing, default)]
    pub nats_connect_password: Option<String>,
    /// External CLI session identifier — NOT renamed per naming convention.
    pub cli_session_id: Option<String>,
    pub model: Option<String>,
    pub provider: Option<String>,
    /// CLI tool that runs inside this agent's container (`claude` / `codex` /
    /// `gemini` / `opencode`). NULL for provider+prompt agents that don't have
    /// a container shell. Used by `containers.rs` to pick the docker image.
    pub cli_tool: Option<String>,
    /// Provider+prompt agent identity (OpenAI Assistants `instructions` analogue).
    /// NULL for CLI-container agents.
    pub system_prompt: Option<String>,
    /// Working directory inside the container. NULL until the runtime reports it.
    pub cwd: Option<String>,
    /// Last tool the agent invoked — refreshed by the event pipeline.
    pub current_tool: Option<String>,
    /// Tokens consumed by the currently-active turn.
    pub tokens_current: i64,
    /// Lifetime token consumption.
    pub tokens_cumulative: i64,
    /// Compact git status hint ("clean", "+3 -1", "M wip/foo.rs").
    pub git_status: Option<String>,
    /// Sidecar/runtime identifier (e.g. "af-XXXXXXXX") — distinct from the DB PK.
    pub runtime_id: Option<String>,
    /// Cached MAX(events.created_at) so the admin list doesn't have to recompute it.
    pub last_activity_at: Option<DateTime<Utc>>,
    pub started_at: Option<DateTime<Utc>>,
    pub ended_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// An event emitted by an agent (persisted from NATS JetStream).
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Event {
    pub id: EventId,
    pub organization_id: OrgId,
    pub agent_id: AgentId,
    pub run_id: Option<Uuid>,
    pub event_type: String,
    pub payload: serde_json::Value,
    /// External CLI session identifier — NOT renamed per naming convention.
    pub session_id: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// A chat message associated with a provider+prompt agent.
///
/// Written by `PromptService` as a pair per turn: one `role="user"` row on
/// prompt submission, one `role="assistant"` row after the LLM stream drains.
/// CASCADE on both org and agent deletes.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AgentMessage {
    pub id: MessageId,
    pub organization_id: OrgId,
    pub agent_id: AgentId,
    pub run_id: Option<Uuid>,
    pub role: String,
    pub content: String,
    pub tokens_in: Option<i32>,
    pub tokens_out: Option<i32>,
    pub model: Option<String>,
    pub finish_reason: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// One execution attempt for an orchestration task assignment.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct TaskRun {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub orchestration_task_id: Uuid,
    pub agent_id: AgentId,
    pub idempotency_key: String,
    pub status: String,
    pub started_at: DateTime<Utc>,
    pub finished_at: Option<DateTime<Utc>>,
    pub capability_profile: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A workspace within an organization.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Workspace {
    pub id: WorkspaceId,
    pub organization_id: OrgId,
    pub name: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

/// A project within a workspace.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Project {
    pub id: ProjectId,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub name: String,
    pub repository_url: Option<String>,
    /// On-disk directory name for this project under the workspace projects
    /// root. Backfilled from `slug`; unique per `(workspace_id, …)` among live
    /// projects.
    pub workspace_dir_name: String,
    /// Coarse clone lifecycle marker: `none`, `queued`, `cloning`, `ready`, or
    /// `failed`. `none` means the project has no associated git clone.
    pub clone_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

/// A single git-clone attempt for a project. One row per attempt; retries
/// increment `attempt`. Holds the runtime, worker-lease, and error detail that
/// the clone worker and reconciler own. Created in milestone M0 (schema only) —
/// no business logic reads or writes this table yet.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ProjectCloneAttempt {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub project_id: ProjectId,
    pub attempt: i32,
    pub repository_url: String,
    pub provider: Option<String>,
    /// Which `git_credentials` row the worker used (never the secret). Internal
    /// forensic detail — `#[serde(skip_serializing)]` so a future direct
    /// serialization of this row can never leak which credential was used. The
    /// API/UI projection is `CloneSummary`, which omits this entirely.
    #[serde(skip_serializing)]
    pub credential_id: Option<Uuid>,
    pub status: String,
    pub resolved_branch: Option<String>,
    pub head_sha: Option<String>,
    /// Deterministic clone container name — operational/diagnostic only. Skipped
    /// from serialization (defense-in-depth; the projection never carries it).
    #[serde(skip_serializing)]
    pub container_id: Option<String>,
    /// The worker that claimed this attempt — internal lease bookkeeping. Skipped.
    #[serde(skip_serializing)]
    pub worker_id: Option<String>,
    /// The `job_queue` row that drove this attempt — internal transport id. Skipped.
    #[serde(skip_serializing)]
    pub job_id: Option<Uuid>,
    /// Worker-lease expiry — internal recovery bookkeeping. Skipped.
    #[serde(skip_serializing)]
    pub lease_expires_at: Option<DateTime<Utc>>,
    pub error_class: Option<String>,
    pub error_message: Option<String>,
    pub bytes_cloned: Option<i64>,
    pub duration_ms: Option<i64>,
    /// Set the instant the cloned tree is renamed live under the projects root,
    /// before the DB finalize-to-`ready` commits. A non-NULL value means the
    /// on-disk publish is irreversible, so a crash/lost-race between the rename
    /// and the finalize is recovered by forcing the attempt to `ready` (the
    /// rename is the source of truth) rather than re-cloning into a refused
    /// already-existing target. See the M5 worker's `finish_ready`.
    pub materialized_at: Option<DateTime<Utc>>,
    pub started_at: Option<DateTime<Utc>>,
    pub finished_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A team within an organization.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Team {
    pub id: TeamId,
    pub organization_id: OrgId,
    pub name: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

/// A job queue entry using the FOR UPDATE SKIP LOCKED pattern.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct JobQueueEntry {
    pub id: Uuid,
    pub queue: String,
    pub payload: serde_json::Value,
    pub status: String,
    pub priority: i32,
    pub run_at: DateTime<Utc>,
    pub attempts: i32,
    pub max_attempts: i32,
    pub locked_by: Option<String>,
    pub locked_at: Option<DateTime<Utc>>,
    pub unique_key: Option<String>,
    pub error_message: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// An API key for programmatic access.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ApiKey {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub name: String,
    #[serde(skip_serializing)]
    pub key_hash: String,
    pub key_prefix: String,
    pub scopes: Vec<String>,
    pub expires_at: Option<DateTime<Utc>>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub revoked_at: Option<DateTime<Utc>>,
}

/// An SSH public key registered by a user.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct SshKey {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub name: String,
    pub public_key: String,
    pub fingerprint: String,
    pub key_type: String,
    pub created_at: DateTime<Utc>,
}

/// A git credential for repository access.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct GitCredential {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub name: String,
    pub provider: String,
    pub credential_type: String,
    #[serde(skip_serializing)]
    pub token_encrypted: Option<Vec<u8>>,
    #[serde(skip_serializing)]
    pub token_nonce: Option<Vec<u8>>,
    pub remote_url: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// LLM provider configuration (per-organization).
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct LlmProviderConfig {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub provider: String,
    pub model: String,
    /// AES-256-GCM encrypted API key bytes.
    #[serde(skip_serializing)]
    pub api_key_encrypted: Option<Vec<u8>>,
    /// AES-256-GCM nonce.
    #[serde(skip_serializing)]
    pub api_key_nonce: Option<Vec<u8>>,
    pub base_url: Option<String>,
    pub is_default: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A billing plan with resource limits.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct BillingPlan {
    pub id: Uuid,
    pub name: String,
    pub stripe_price_id: Option<String>,
    pub max_agents: i32,
    pub max_events_per_day: i32,
    pub max_storage_mb: i32,
    pub features: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// An organization's subscription to a billing plan.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Subscription {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub plan_id: Uuid,
    #[serde(skip_serializing)]
    pub stripe_subscription_id: Option<String>,
    #[serde(skip_serializing)]
    pub stripe_customer_id: Option<String>,
    pub status: String,
    pub current_period_start: Option<DateTime<Utc>>,
    pub current_period_end: Option<DateTime<Utc>>,
    pub cancel_at_period_end: bool,
    pub canceled_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// An invoice for a subscription.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Invoice {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub subscription_id: Option<Uuid>,
    pub stripe_invoice_id: Option<String>,
    pub amount_cents: i32,
    pub currency: String,
    pub status: String,
    pub paid_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

/// A key-value setting scoped to an organization or user.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Setting {
    pub id: SettingId,
    pub organization_id: OrgId,
    pub user_id: Option<UserId>,
    pub key: String,
    pub value: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A feature flag, optionally scoped to an organization.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct FeatureFlag {
    pub id: FeatureFlagId,
    pub organization_id: Option<OrgId>,
    pub name: String,
    pub enabled: bool,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A user's favorite (bookmarked) resource.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Favorite {
    pub id: FavoriteId,
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub target_type: String,
    pub target_id: Uuid,
    pub created_at: DateTime<Utc>,
}

/// An audit log entry recording a user action.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AuditLogEntry {
    pub id: AuditLogId,
    pub organization_id: OrgId,
    pub user_id: Option<UserId>,
    pub action: String,
    pub resource_type: String,
    pub resource_id: Option<Uuid>,
    pub details: serde_json::Value,
    pub ip_address: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// An orchestration task for A2A multi-agent dispatch.
///
/// Kanban states: `backlog | queued | working | blocked | completed | failed | canceled`.
/// `blocked_reason` + `blocked_metadata` describe what the task is waiting on so the
/// UI can render a "还差什么" hint without re-deriving it from joins.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct OrchestrationTask {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub group_id: Option<Uuid>,
    pub title: String,
    pub description: Option<String>,
    pub status: String,
    pub priority: String,
    pub progress: i16,
    pub params: Option<serde_json::Value>,
    pub created_by: UserId,
    pub assigned_agent_id: Option<AgentId>,
    pub parent_task_id: Option<Uuid>,
    pub result: Option<serde_json::Value>,
    pub error: Option<serde_json::Value>,
    pub blocked_reason: Option<String>,
    pub blocked_metadata: Option<serde_json::Value>,
    pub requires_approval: bool,
    pub approved_at: Option<DateTime<Utc>>,
    pub approved_by: Option<UserId>,
    pub attempt: i32,
    pub lease_expires_at: Option<DateTime<Utc>>,
    pub failure_code: Option<String>,
    pub retryable: bool,
    pub last_assignment_id: Option<Uuid>,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub canceled_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct OrchestrationOutbox {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub aggregate_type: String,
    pub aggregate_id: Uuid,
    pub event_type: String,
    pub payload: serde_json::Value,
    pub published_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct OrchestrationInbox {
    pub delivery_id: Uuid,
    pub organization_id: OrgId,
    pub task_id: Uuid,
    pub message_type: String,
    pub processed_at: DateTime<Utc>,
}

/// A participant — an agent registered for A2A orchestration.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Participant {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub agent_id: AgentId,
    pub name: String,
    pub capabilities: Vec<String>,
    pub status: String,
    pub registered_at: DateTime<Utc>,
    pub last_heartbeat_at: Option<DateTime<Utc>>,
}

/// A group within an organization (for multi-user management).
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Group {
    pub id: GroupId,
    pub organization_id: OrgId,
    pub project_id: Option<ProjectId>,
    pub name: String,
    pub description: Option<String>,
    pub created_by: UserId,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

/// A membership record linking a user to a group.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct GroupMember {
    pub group_id: GroupId,
    pub user_id: UserId,
    pub role: String,
    pub created_at: DateTime<Utc>,
}

/// A collaborator record linking a user to an agent with a permission level.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AgentCollaborator {
    pub agent_id: AgentId,
    pub user_id: UserId,
    pub permission: String,
    pub created_at: DateTime<Utc>,
}

/// An impersonation log entry recording admin impersonation of another user.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ImpersonationLog {
    pub id: Uuid,
    pub admin_user_id: UserId,
    pub target_user_id: UserId,
    pub organization_id: OrgId,
    pub reason: Option<String>,
    pub started_at: DateTime<Utc>,
    pub ended_at: Option<DateTime<Utc>>,
}

/// A plugin (global or org-scoped).
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Plugin {
    pub id: PluginId,
    pub organization_id: Option<OrgId>,
    pub name: String,
    pub version: String,
    pub description: Option<String>,
    pub config: serde_json::Value,
    pub enabled: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A skill (prompt template with optional trigger).
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Skill {
    pub id: SkillId,
    pub organization_id: Option<OrgId>,
    pub workspace_id: Option<WorkspaceId>,
    pub scope_kind: Option<String>,
    pub scope_id: Option<Uuid>,
    pub name: String,
    pub description: Option<String>,
    pub trigger_pattern: Option<String>,
    pub content: String,
    pub enabled: bool,
    pub state: String,
    pub version: i32,
    pub owner_user_id: Option<UserId>,
    pub ttl_expires_at: Option<DateTime<Utc>>,
    pub sensitivity: String,
    pub provenance: serde_json::Value,
    pub negative_trigger: Option<String>,
    pub required_inputs: serde_json::Value,
    pub tools: serde_json::Value,
    pub examples: serde_json::Value,
    pub success_evidence: serde_json::Value,
    pub revoked_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Append-only snapshot of a governed skill before a mutation.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct SkillVersion {
    pub id: Uuid,
    pub skill_id: SkillId,
    pub version: i32,
    pub snapshot: serde_json::Value,
    pub author_user_id: UserId,
    pub created_at: DateTime<Utc>,
}

/// Governed memory asset used by the context layer.
#[derive(Clone, Serialize, Deserialize, FromRow)]
pub struct MemoryItem {
    pub id: MemoryItemId,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub owner_user_id: UserId,
    pub scope_kind: String,
    pub scope_id: Uuid,
    pub source_task_id: Option<Uuid>,
    pub source_run_id: Option<Uuid>,
    pub title: String,
    #[serde(skip_serializing)]
    pub content: String,
    pub content_redacted: bool,
    pub content_encrypted: bool,
    pub visibility: String,
    pub sensitivity: String,
    pub provenance: serde_json::Value,
    pub ttl_expires_at: Option<DateTime<Utc>>,
    pub confidence: Option<f64>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub last_verified_at: Option<DateTime<Utc>>,
    pub state: String,
    pub revoked_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl std::fmt::Debug for MemoryItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MemoryItem")
            .field("id", &self.id)
            .field("organization_id", &self.organization_id)
            .field("workspace_id", &self.workspace_id)
            .field("owner_user_id", &self.owner_user_id)
            .field("scope_kind", &self.scope_kind)
            .field("scope_id", &self.scope_id)
            .field("source_task_id", &self.source_task_id)
            .field("source_run_id", &self.source_run_id)
            .field("title", &self.title)
            .field("content", &format_args!("<redacted; len={}>", self.content.len()))
            .field("content_redacted", &self.content_redacted)
            .field("content_encrypted", &self.content_encrypted)
            .field("visibility", &self.visibility)
            .field("sensitivity", &self.sensitivity)
            .field("provenance", &self.provenance)
            .field("ttl_expires_at", &self.ttl_expires_at)
            .field("confidence", &self.confidence)
            .field("last_used_at", &self.last_used_at)
            .field("last_verified_at", &self.last_verified_at)
            .field("state", &self.state)
            .field("revoked_at", &self.revoked_at)
            .field("created_at", &self.created_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

/// Raw extraction output awaiting human approval.
#[derive(Clone, Serialize, Deserialize, FromRow)]
pub struct ContextCandidate {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub source_run_id: Option<Uuid>,
    pub target_skill_id: Option<SkillId>,
    pub item_kind: String,
    #[serde(skip_serializing)]
    pub proposed_content: serde_json::Value,
    pub state: String,
    pub owner_user_id: UserId,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl std::fmt::Debug for ContextCandidate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ContextCandidate")
            .field("id", &self.id)
            .field("organization_id", &self.organization_id)
            .field("workspace_id", &self.workspace_id)
            .field("source_run_id", &self.source_run_id)
            .field("target_skill_id", &self.target_skill_id)
            .field("item_kind", &self.item_kind)
            .field("proposed_content", &format_args!("<redacted; bytes={}>", self.proposed_content.to_string().len()))
            .field("state", &self.state)
            .field("owner_user_id", &self.owner_user_id)
            .field("created_at", &self.created_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

/// Human approval or rejection decision for a context candidate.
#[derive(Clone, Serialize, Deserialize, FromRow)]
pub struct ContextApproval {
    pub id: Uuid,
    pub candidate_id: Uuid,
    pub approver_user_id: UserId,
    pub decision: String,
    pub scope_kind: Option<String>,
    pub scope_id: Option<Uuid>,
    pub ttl_at: Option<DateTime<Utc>>,
    pub sensitivity: Option<String>,
    pub reason: Option<String>,
    pub self_approval: bool,
    pub user_attest_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

impl std::fmt::Debug for ContextApproval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ContextApproval")
            .field("id", &self.id)
            .field("candidate_id", &self.candidate_id)
            .field("approver_user_id", &self.approver_user_id)
            .field("decision", &self.decision)
            .field("scope_kind", &self.scope_kind)
            .field("scope_id", &self.scope_id)
            .field("ttl_at", &self.ttl_at)
            .field("sensitivity", &self.sensitivity)
            .field("reason", &self.reason)
            .field("self_approval", &self.self_approval)
            .field("user_attest_at", &self.user_attest_at)
            .field("created_at", &self.created_at)
            .finish()
    }
}

/// Provenance edge between a governed context item and a task/run/source.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ContextLink {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub item_id: Uuid,
    pub item_kind: String,
    pub ref_id: Uuid,
    pub ref_kind: String,
    pub link_type: String,
    pub created_by_user_id: UserId,
    pub created_at: DateTime<Utc>,
}

/// Per-user feedback for one context item in one run.
#[derive(Clone, Serialize, Deserialize, FromRow)]
pub struct ContextFeedback {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub run_id: Uuid,
    pub item_id: Uuid,
    pub item_kind: String,
    pub label: String,
    pub note: Option<String>,
    pub user_id: UserId,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl std::fmt::Debug for ContextFeedback {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ContextFeedback")
            .field("id", &self.id)
            .field("organization_id", &self.organization_id)
            .field("workspace_id", &self.workspace_id)
            .field("run_id", &self.run_id)
            .field("item_id", &self.item_id)
            .field("item_kind", &self.item_kind)
            .field("label", &self.label)
            .field("note", &self.note.as_ref().map(|note| format!("<redacted; len={}>", note.len())))
            .field("user_id", &self.user_id)
            .field("created_at", &self.created_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

/// Immutable publish-time preview of the context resolver output.
#[derive(Clone, Serialize, Deserialize, FromRow)]
pub struct ContextPreview {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub task_id: Uuid,
    pub agent_id: AgentId,
    pub created_by_user_id: UserId,
    pub task_draft_hash: String,
    pub preview_hash: String,
    #[serde(skip_serializing)]
    pub selected_items: serde_json::Value,
    pub removed_item_ids: Vec<Uuid>,
    pub pinned_item_ids: Vec<Uuid>,
    pub expires_at: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
}

impl std::fmt::Debug for ContextPreview {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ContextPreview")
            .field("id", &self.id)
            .field("organization_id", &self.organization_id)
            .field("workspace_id", &self.workspace_id)
            .field("task_id", &self.task_id)
            .field("agent_id", &self.agent_id)
            .field("created_by_user_id", &self.created_by_user_id)
            .field("task_draft_hash", &self.task_draft_hash)
            .field("preview_hash", &self.preview_hash)
            .field("selected_items", &format_args!("<redacted; bytes={}>", self.selected_items.to_string().len()))
            .field("removed_item_ids", &self.removed_item_ids)
            .field("pinned_item_ids", &self.pinned_item_ids)
            .field("expires_at", &self.expires_at)
            .field("created_at", &self.created_at)
            .finish()
    }
}

/// Immutable fact row for one context item applied to one run.
#[derive(Clone, Serialize, Deserialize, FromRow)]
pub struct RunContextInjection {
    pub id: Uuid,
    pub organization_id: OrgId,
    pub workspace_id: WorkspaceId,
    pub run_id: Uuid,
    pub item_id: Uuid,
    pub item_kind: String,
    pub position: i32,
    pub adapter: String,
    pub envelope_version: String,
    pub capability_profile: serde_json::Value,
    #[serde(skip_serializing)]
    pub applied_snapshot: serde_json::Value,
    pub degradation_reason: Option<String>,
    pub applied_at: DateTime<Utc>,
}

impl std::fmt::Debug for RunContextInjection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RunContextInjection")
            .field("id", &self.id)
            .field("organization_id", &self.organization_id)
            .field("workspace_id", &self.workspace_id)
            .field("run_id", &self.run_id)
            .field("item_id", &self.item_id)
            .field("item_kind", &self.item_kind)
            .field("position", &self.position)
            .field("adapter", &self.adapter)
            .field("envelope_version", &self.envelope_version)
            .field("capability_profile", &self.capability_profile)
            .field("applied_snapshot", &format_args!("<redacted; bytes={}>", self.applied_snapshot.to_string().len()))
            .field("degradation_reason", &self.degradation_reason)
            .field("applied_at", &self.applied_at)
            .finish()
    }
}

/// An analytics event for tracking usage.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AnalyticsEvent {
    pub id: AnalyticsEventId,
    pub organization_id: OrgId,
    pub user_id: Option<UserId>,
    pub event_name: String,
    pub properties: serde_json::Value,
    pub created_at: DateTime<Utc>,
}

/// A software license for an organization.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct License {
    pub id: LicenseId,
    pub organization_id: OrgId,
    pub license_key: String,
    pub plan_name: String,
    pub max_agents: i32,
    pub max_users: i32,
    pub valid_from: DateTime<Utc>,
    pub valid_until: Option<DateTime<Utc>>,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A voice provider configuration.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct VoiceProvider {
    pub id: VoiceProviderId,
    pub organization_id: OrgId,
    pub name: String,
    pub provider_type: String,
    pub config: serde_json::Value,
    pub is_default: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A dashboard tile for layout customization.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Tile {
    pub id: TileId,
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub tile_type: String,
    pub config: serde_json::Value,
    pub position_x: i32,
    pub position_y: i32,
    pub width: i32,
    pub height: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A saved prompt template.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Prompt {
    pub id: PromptId,
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub title: String,
    pub content: String,
    pub tags: Vec<String>,
    pub is_shared: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A file attachment stored via local or MinIO backend.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Attachment {
    pub id: AttachmentId,
    pub organization_id: OrgId,
    pub user_id: UserId,
    pub agent_id: Option<AgentId>,
    pub run_id: Option<Uuid>,
    pub filename: String,
    pub content_type: String,
    pub size_bytes: i64,
    pub storage_path: String,
    pub storage_backend: String,
    pub created_at: DateTime<Utc>,
}

/// A resource profile defining container resource limits.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ResourceProfile {
    pub id: ResourceProfileId,
    /// NULL means system default (not org-scoped).
    pub organization_id: Option<OrgId>,
    pub name: String,
    pub cpu_millicores: i32,
    pub memory_mb: i32,
    pub storage_mb: i32,
    pub max_pids: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Quota usage tracking for an organization's resources.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct QuotaUsage {
    pub id: QuotaUsageId,
    pub organization_id: OrgId,
    pub resource_type: String,
    pub current_usage: i64,
    pub max_allowed: i64,
    pub updated_at: DateTime<Utc>,
}

/// A development environment managed by the platform.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct DevEnvironment {
    pub id: DevEnvironmentId,
    pub organization_id: OrgId,
    pub project_id: Option<ProjectId>,
    pub name: String,
    pub config: serde_json::Value,
    pub status: String,
    pub container_id: Option<String>,
    pub created_by: UserId,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use agentforge_core::{
        AgentId, AgentStatus, AttachmentId, AuditLogId, DevEnvironmentId, EventId, FavoriteId, FeatureFlagId, GroupId,
        OrgId, ProjectId, PromptId, QuotaUsageId, ResourceProfileId, SettingId, UserId, WorkspaceId,
    };

    #[test]
    fn organization_serialization_roundtrip() {
        let org = Organization {
            id: OrgId::new(),
            name: "Test Org".to_string(),
            slug: "test-org".to_string(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
        };
        let json = serde_json::to_string(&org).unwrap();
        let deserialized: Organization = serde_json::from_str(&json).unwrap();
        assert_eq!(org.id, deserialized.id);
        assert_eq!(org.name, deserialized.name);
        assert_eq!(org.slug, deserialized.slug);
    }

    #[test]
    fn agent_serialization_roundtrip() {
        let agent = Agent {
            id: AgentId::new(),
            organization_id: OrgId::new(),
            workspace_id: WorkspaceId::new(),
            project_id: Some(ProjectId::new()),
            user_id: UserId::new(),
            name: Some("claude-dev".to_string()),
            status: AgentStatus::Working,
            container_id: Some("abc123".to_string()),
            hmac_secret: Some("fixture-hmac".to_string()),
            nats_connect_password: Some("fixture-nats-pw".to_string()),
            cli_session_id: Some("cli-sess-456".to_string()),
            model: Some("claude-sonnet-4-20250514".to_string()),
            provider: Some("anthropic".to_string()),
            cli_tool: Some("claude".to_string()),
            system_prompt: None,
            cwd: Some("/workspaces/demo".to_string()),
            current_tool: Some("Edit".to_string()),
            tokens_current: 1234,
            tokens_cumulative: 56789,
            git_status: Some("clean".to_string()),
            runtime_id: Some("af-12345678".to_string()),
            last_activity_at: Some(Utc::now()),
            started_at: Some(Utc::now()),
            ended_at: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&agent).unwrap();
        let deserialized: Agent = serde_json::from_str(&json).unwrap();
        assert_eq!(agent.id, deserialized.id);
        assert_eq!(agent.status, deserialized.status);
        assert_eq!(agent.cli_session_id, deserialized.cli_session_id);

        // Regression guard: the two per-container secrets MUST NOT appear
        // in serialized output. Agent is returned by every GET /agents
        // endpoint; a leak here hands the sidecar's NATS credential or
        // envelope HMAC to the tenant via the normal API surface.
        // `hmac_secret` closes #39; `nats_connect_password` closes #38
        // phase 2. Both rely on `#[serde(skip_serializing)]` on the
        // entity field. Dropping the attribute must break this test.
        assert!(!json.contains("fixture-hmac"), "hmac_secret leaked into JSON: {json}");
        assert!(!json.contains("fixture-nats-pw"), "nats_connect_password leaked into JSON: {json}");
        assert!(!json.contains("hmac_secret"), "hmac_secret field name leaked into JSON: {json}");
        assert!(!json.contains("nats_connect_password"), "nats_connect_password field name leaked into JSON: {json}");
    }

    #[test]
    fn event_with_json_payload() {
        let event = Event {
            id: EventId::new(),
            organization_id: OrgId::new(),
            agent_id: AgentId::new(),
            run_id: None,
            event_type: "pre_tool_use".to_string(),
            payload: serde_json::json!({"tool": "Read", "path": "/tmp/test.rs"}),
            session_id: Some("cli-sess-789".to_string()),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&event).unwrap();
        let deserialized: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event.id, deserialized.id);
        assert_eq!(event.event_type, deserialized.event_type);
        assert_eq!(event.payload["tool"], "Read");
    }

    #[test]
    fn job_queue_entry_defaults() {
        let job = JobQueueEntry {
            id: Uuid::now_v7(),
            queue: "cleanup".to_string(),
            payload: serde_json::json!({}),
            status: "pending".to_string(),
            priority: 0,
            run_at: Utc::now(),
            attempts: 0,
            max_attempts: 3,
            locked_by: None,
            locked_at: None,
            unique_key: None,
            error_message: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&job).unwrap();
        let deserialized: JobQueueEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.status, "pending");
        assert_eq!(deserialized.attempts, 0);
    }

    #[test]
    fn user_with_optional_fields() {
        let user = User {
            id: UserId::new(),
            email: "dev@example.com".to_string(),
            password_hash: Some("$argon2id$secret".to_string()),
            display_name: None,
            is_admin: false,
            last_login_at: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
        };
        let json = serde_json::to_string(&user).unwrap();
        // password_hash must NOT appear in serialized JSON
        assert!(!json.contains("password_hash"));
        assert!(!json.contains("argon2id"));
        let value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(value["email"], "dev@example.com");
        assert_eq!(value["is_admin"], false);
    }

    #[test]
    fn workspace_and_project_hierarchy() {
        let org_id = OrgId::new();
        let ws_id = WorkspaceId::new();

        let ws = Workspace {
            id: ws_id,
            organization_id: org_id,
            name: "Default Workspace".to_string(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
        };

        let proj = Project {
            id: ProjectId::new(),
            organization_id: org_id,
            workspace_id: ws_id,
            name: "Wisdoverse Forge".to_string(),
            repository_url: Some("https://github.com/Wisdoverse/Wisdoverse-Forge".to_string()),
            workspace_dir_name: "wisdoverse-forge".to_string(),
            clone_status: "none".to_string(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
        };

        // Verify org scoping matches
        assert_eq!(ws.organization_id, proj.organization_id);
        assert_eq!(ws.id, proj.workspace_id);
    }

    #[test]
    fn llm_provider_config_with_encrypted_key() {
        let config = LlmProviderConfig {
            id: Uuid::now_v7(),
            organization_id: OrgId::new(),
            provider: "anthropic".to_string(),
            model: "claude-sonnet-4-20250514".to_string(),
            api_key_encrypted: Some(vec![0xDE, 0xAD, 0xBE, 0xEF]),
            api_key_nonce: Some(vec![0x01, 0x02, 0x03]),
            base_url: None,
            is_default: true,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&config).unwrap();
        // Encrypted key fields must NOT appear in serialized JSON
        assert!(!json.contains("api_key_encrypted"));
        assert!(!json.contains("api_key_nonce"));
        let value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(value["provider"], "anthropic");
        assert_eq!(value["is_default"], true);
    }

    #[test]
    fn api_key_hides_hash_in_serialization() {
        let key = ApiKey {
            id: Uuid::now_v7(),
            organization_id: OrgId::new(),
            user_id: UserId::new(),
            name: "CI Key".to_string(),
            key_hash: "abc123hash".to_string(),
            key_prefix: "af_abcd".to_string(),
            scopes: vec!["read".to_string(), "write".to_string()],
            expires_at: None,
            last_used_at: None,
            created_at: Utc::now(),
            revoked_at: None,
        };
        let json = serde_json::to_string(&key).unwrap();
        // key_hash must NOT appear in serialized JSON
        assert!(!json.contains("key_hash"));
        assert!(!json.contains("abc123hash"));
        let value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(value["key_prefix"], "af_abcd");
        assert_eq!(value["scopes"], serde_json::json!(["read", "write"]));
    }

    #[test]
    fn ssh_key_serialization_roundtrip() {
        let key = SshKey {
            id: Uuid::now_v7(),
            organization_id: OrgId::new(),
            user_id: UserId::new(),
            name: "My Key".to_string(),
            public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5 dev@example.com".to_string(),
            fingerprint: "SHA256:abc123".to_string(),
            key_type: "ed25519".to_string(),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&key).unwrap();
        let deserialized: SshKey = serde_json::from_str(&json).unwrap();
        assert_eq!(key.id, deserialized.id);
        assert_eq!(key.fingerprint, deserialized.fingerprint);
    }

    #[test]
    fn git_credential_hides_token_in_serialization() {
        let cred = GitCredential {
            id: Uuid::now_v7(),
            organization_id: OrgId::new(),
            user_id: UserId::new(),
            name: "GitHub Token".to_string(),
            provider: "github".to_string(),
            credential_type: "token".to_string(),
            token_encrypted: Some(vec![0xDE, 0xAD]),
            token_nonce: Some(vec![0x01, 0x02]),
            remote_url: Some("https://github.com/org/repo".to_string()),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&cred).unwrap();
        // Encrypted token fields must NOT appear in serialized JSON
        assert!(!json.contains("token_encrypted"));
        assert!(!json.contains("token_nonce"));
        let value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(value["provider"], "github");
        assert_eq!(value["credential_type"], "token");
    }

    #[test]
    fn billing_plan_serialization_roundtrip() {
        let plan = BillingPlan {
            id: Uuid::now_v7(),
            name: "free".to_string(),
            stripe_price_id: None,
            max_agents: 3,
            max_events_per_day: 1000,
            max_storage_mb: 256,
            features: serde_json::json!({"basic": true}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&plan).unwrap();
        let deserialized: BillingPlan = serde_json::from_str(&json).unwrap();
        assert_eq!(plan.id, deserialized.id);
        assert_eq!(plan.name, deserialized.name);
        assert_eq!(plan.max_agents, 3);
        assert_eq!(deserialized.features["basic"], true);
    }

    #[test]
    fn subscription_serialization_roundtrip() {
        let sub = Subscription {
            id: Uuid::now_v7(),
            organization_id: OrgId::new(),
            plan_id: Uuid::now_v7(),
            stripe_subscription_id: Some("sub_abc123".to_string()),
            stripe_customer_id: Some("cus_xyz789".to_string()),
            status: "active".to_string(),
            current_period_start: Some(Utc::now()),
            current_period_end: Some(Utc::now()),
            cancel_at_period_end: false,
            canceled_at: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&sub).unwrap();
        // Stripe IDs must NOT appear in serialized JSON
        assert!(!json.contains("stripe_subscription_id"));
        assert!(!json.contains("sub_abc123"));
        assert!(!json.contains("stripe_customer_id"));
        assert!(!json.contains("cus_xyz789"));
        let value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(sub.id.to_string(), value["id"].as_str().unwrap());
        assert_eq!(value["status"], "active");
    }

    #[test]
    fn invoice_serialization_roundtrip() {
        let inv = Invoice {
            id: Uuid::now_v7(),
            organization_id: OrgId::new(),
            subscription_id: Some(Uuid::now_v7()),
            stripe_invoice_id: Some("inv_abc".to_string()),
            amount_cents: 2999,
            currency: "usd".to_string(),
            status: "paid".to_string(),
            paid_at: Some(Utc::now()),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&inv).unwrap();
        let deserialized: Invoice = serde_json::from_str(&json).unwrap();
        assert_eq!(inv.id, deserialized.id);
        assert_eq!(deserialized.amount_cents, 2999);
        assert_eq!(deserialized.currency, "usd");
    }

    #[test]
    fn setting_serialization_roundtrip() {
        let setting = Setting {
            id: SettingId::new(),
            organization_id: OrgId::new(),
            user_id: Some(UserId::new()),
            key: "theme".to_string(),
            value: serde_json::json!({"mode": "dark"}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&setting).unwrap();
        let deserialized: Setting = serde_json::from_str(&json).unwrap();
        assert_eq!(setting.id, deserialized.id);
        assert_eq!(deserialized.key, "theme");
        assert_eq!(deserialized.value["mode"], "dark");
    }

    #[test]
    fn feature_flag_serialization_roundtrip() {
        let flag = FeatureFlag {
            id: FeatureFlagId::new(),
            organization_id: Some(OrgId::new()),
            name: "dark-mode".to_string(),
            enabled: true,
            metadata: serde_json::json!({"rollout_pct": 50}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&flag).unwrap();
        let deserialized: FeatureFlag = serde_json::from_str(&json).unwrap();
        assert_eq!(flag.id, deserialized.id);
        assert_eq!(deserialized.name, "dark-mode");
        assert!(deserialized.enabled);
    }

    #[test]
    fn favorite_serialization_roundtrip() {
        let fav = Favorite {
            id: FavoriteId::new(),
            organization_id: OrgId::new(),
            user_id: UserId::new(),
            target_type: "project".to_string(),
            target_id: Uuid::now_v7(),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&fav).unwrap();
        let deserialized: Favorite = serde_json::from_str(&json).unwrap();
        assert_eq!(fav.id, deserialized.id);
        assert_eq!(deserialized.target_type, "project");
    }

    #[test]
    fn audit_log_entry_serialization_roundtrip() {
        let entry = AuditLogEntry {
            id: AuditLogId::new(),
            organization_id: OrgId::new(),
            user_id: Some(UserId::new()),
            action: "create".to_string(),
            resource_type: "agent".to_string(),
            resource_id: Some(Uuid::now_v7()),
            details: serde_json::json!({"name": "test-agent"}),
            ip_address: Some("192.168.1.1".to_string()),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: AuditLogEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry.id, deserialized.id);
        assert_eq!(deserialized.action, "create");
        assert_eq!(deserialized.resource_type, "agent");
    }

    #[test]
    fn group_serialization_roundtrip() {
        let group = Group {
            id: GroupId::new(),
            organization_id: OrgId::new(),
            project_id: Some(ProjectId::new()),
            name: "Backend Team".to_string(),
            description: Some("Backend engineers".to_string()),
            created_by: UserId::new(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
        };
        let json = serde_json::to_string(&group).unwrap();
        let deserialized: Group = serde_json::from_str(&json).unwrap();
        assert_eq!(group.id, deserialized.id);
        assert_eq!(deserialized.name, "Backend Team");
        assert_eq!(deserialized.description.as_deref(), Some("Backend engineers"));
    }

    #[test]
    fn group_member_serialization_roundtrip() {
        let member = GroupMember {
            group_id: GroupId::new(),
            user_id: UserId::new(),
            role: "admin".to_string(),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&member).unwrap();
        let deserialized: GroupMember = serde_json::from_str(&json).unwrap();
        assert_eq!(member.group_id, deserialized.group_id);
        assert_eq!(deserialized.role, "admin");
    }

    #[test]
    fn agent_collaborator_serialization_roundtrip() {
        let collab = AgentCollaborator {
            agent_id: AgentId::new(),
            user_id: UserId::new(),
            permission: "edit".to_string(),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&collab).unwrap();
        let deserialized: AgentCollaborator = serde_json::from_str(&json).unwrap();
        assert_eq!(collab.agent_id, deserialized.agent_id);
        assert_eq!(deserialized.permission, "edit");
    }

    #[test]
    fn impersonation_log_serialization_roundtrip() {
        let log = ImpersonationLog {
            id: Uuid::now_v7(),
            admin_user_id: UserId::new(),
            target_user_id: UserId::new(),
            organization_id: OrgId::new(),
            reason: Some("Debug user issue".to_string()),
            started_at: Utc::now(),
            ended_at: None,
        };
        let json = serde_json::to_string(&log).unwrap();
        let deserialized: ImpersonationLog = serde_json::from_str(&json).unwrap();
        assert_eq!(log.id, deserialized.id);
        assert_eq!(deserialized.reason.as_deref(), Some("Debug user issue"));
        assert!(deserialized.ended_at.is_none());
    }

    #[test]
    fn prompt_serialization_roundtrip() {
        let prompt = Prompt {
            id: PromptId::new(),
            organization_id: OrgId::new(),
            user_id: UserId::new(),
            title: "Code Review".to_string(),
            content: "Review this code for security issues".to_string(),
            tags: vec!["review".to_string(), "security".to_string()],
            is_shared: true,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&prompt).unwrap();
        let deserialized: Prompt = serde_json::from_str(&json).unwrap();
        assert_eq!(prompt.id, deserialized.id);
        assert_eq!(deserialized.title, "Code Review");
        assert_eq!(deserialized.tags.len(), 2);
        assert!(deserialized.is_shared);
    }

    #[test]
    fn attachment_serialization_roundtrip() {
        let att = Attachment {
            id: AttachmentId::new(),
            organization_id: OrgId::new(),
            user_id: UserId::new(),
            agent_id: Some(AgentId::new()),
            run_id: None,
            filename: "report.pdf".to_string(),
            content_type: "application/pdf".to_string(),
            size_bytes: 1048576,
            storage_path: "/uploads/report.pdf".to_string(),
            storage_backend: "local".to_string(),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&att).unwrap();
        let deserialized: Attachment = serde_json::from_str(&json).unwrap();
        assert_eq!(att.id, deserialized.id);
        assert_eq!(deserialized.filename, "report.pdf");
        assert_eq!(deserialized.size_bytes, 1048576);
    }

    #[test]
    fn resource_profile_serialization_roundtrip() {
        let rp = ResourceProfile {
            id: ResourceProfileId::new(),
            organization_id: Some(OrgId::new()),
            name: "large".to_string(),
            cpu_millicores: 4000,
            memory_mb: 8192,
            storage_mb: 10240,
            max_pids: 512,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&rp).unwrap();
        let deserialized: ResourceProfile = serde_json::from_str(&json).unwrap();
        assert_eq!(rp.id, deserialized.id);
        assert_eq!(deserialized.name, "large");
        assert_eq!(deserialized.cpu_millicores, 4000);
    }

    #[test]
    fn quota_usage_serialization_roundtrip() {
        let qu = QuotaUsage {
            id: QuotaUsageId::new(),
            organization_id: OrgId::new(),
            resource_type: "agents".to_string(),
            current_usage: 5,
            max_allowed: 10,
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&qu).unwrap();
        let deserialized: QuotaUsage = serde_json::from_str(&json).unwrap();
        assert_eq!(qu.id, deserialized.id);
        assert_eq!(deserialized.resource_type, "agents");
        assert_eq!(deserialized.current_usage, 5);
    }

    #[test]
    fn dev_environment_serialization_roundtrip() {
        let de = DevEnvironment {
            id: DevEnvironmentId::new(),
            organization_id: OrgId::new(),
            project_id: Some(ProjectId::new()),
            name: "dev-env-1".to_string(),
            config: serde_json::json!({"image": "ubuntu:22.04"}),
            status: "stopped".to_string(),
            container_id: None,
            created_by: UserId::new(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&de).unwrap();
        let deserialized: DevEnvironment = serde_json::from_str(&json).unwrap();
        assert_eq!(de.id, deserialized.id);
        assert_eq!(deserialized.name, "dev-env-1");
        assert_eq!(deserialized.status, "stopped");
        assert_eq!(deserialized.config["image"], "ubuntu:22.04");
    }
}
