-- Per-agent HMAC secret, persisted at container spawn so the backend result
-- consumer can verify `SignedEnvelope` signatures. Before this column, the
-- sidecar signed every TaskResult but the consumer ignored the signature —
-- issue #39 closes that gap alongside #38's subject scoping.
--
-- Nullable on purpose: existing rows (agents spawned before this migration)
-- have no stored secret; the consumer rejects their envelopes, the next
-- start_agent rewrites the row with a fresh UUID. Empty string is NOT
-- treated as a secret — the repo write binds a generated value every time.
--
-- TEXT (not BYTEA): matches how the sidecar receives it (env var), keeps
-- the ops story simple (`psql \d agents` shows a clean hex literal),
-- and the column is never compared for equality — only fetched and handed
-- to `SignedEnvelope::verify` which does constant-time comparison via the
-- `hmac` crate.
ALTER TABLE agents ADD COLUMN IF NOT EXISTS hmac_secret TEXT;

COMMENT ON COLUMN agents.hmac_secret IS
    'Per-container HMAC-SHA256 key (issue #39). Generated by start_agent, '
    'injected into the sidecar as HMAC_SECRET, used by '
    'orchestration_result_consumer to verify TaskResult envelopes. '
    'NULL for agents spawned before migration 025 or for provider+prompt '
    'agents that have no container.';
