-- Per-agent NATS connect password (issue #38 phase 2).
--
-- Phase 1 of #38 split the shared NATS_TOKEN into role-scoped users
-- (backend, agent). Every spawned container still got the SAME `agent`
-- password, so a compromised sidecar could publish/subscribe against
-- any other agent's per-agent subjects (orchestration.result.<other>,
-- orchestration.assigned.>). Phase 2 replaces the shared role with
-- dynamic per-agent identities minted by an auth callout service; this
-- column holds the per-container password that the callout compares
-- against the `user=<agent_uuid>` the sidecar presents on CONNECT.
--
-- Separate from hmac_secret: that column is the envelope signing key
-- for SignedEnvelope verification (#39). Keeping them in different
-- columns means a DB read that leaks one secret does not also grant
-- the other attacker surface (subject authorization vs. envelope
-- forgery). Defence-in-depth is cheap at the storage layer.
--
-- Nullable on purpose: existing rows (agents spawned before this
-- migration, or provider+prompt agents with no container) have no
-- stored password. start_agent rewrites the row with a fresh UUID on
-- every container spawn. Empty string is NOT treated as a secret —
-- the repo write binds a generated value every time. clear_container
-- NULLs this column first, then hmac_secret, so an interrupted stop
-- still disables NATS auth before envelope verification.
--
-- TEXT (not BYTEA): matches how the sidecar receives it (embedded in
-- NATS_URL env var), keeps the ops story simple (`psql \d agents`
-- shows a clean UUID string), and the column is never compared for
-- equality in SQL — only fetched and handed to a constant-time
-- comparator at the callout layer.
ALTER TABLE agents ADD COLUMN IF NOT EXISTS nats_connect_password TEXT;

COMMENT ON COLUMN agents.nats_connect_password IS
    'Per-container password used by NATS auth callout (issue #38 phase 2). '
    'Generated by start_agent, injected into the sidecar as part of NATS_URL '
    'user info, validated by services::auth_callout against the '
    '`user=<agent_uuid>` presented on CONNECT. NULL for agents spawned '
    'before migration 028 or for provider+prompt agents that have no '
    'container. Cleared atomically with hmac_secret in clear_container.';
